#!/bin/sh
# # x-make -- POSIX make on x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus AWK,
#   with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# The launcher-free boot amalgam: an install has it at boot/, a checkout
# builds it into build/boot/.  lib/x-base.x is NOT a substitute -- it opens
# with a root-relative include.  (Same probe as x-ash; see its notes.)
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-make: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# %install-root FIRST (deferred imports resolve against it), the amalgam
# (never a dialect entry -- those end by starting a REPL), then the bundle
# root armed exactly as run.x arms it.  Nothing under make/ includes anything
# from the platform: re-including a platform module on a booted tower is a
# segfault, not an error (x-lang#515).
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
(import mk/base)
(set! %repl-print %make-repl-print)
EOF
